# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Rahul Krishna
description:         <h3 class="">Hello! I'm Rahul Krishna.</h3><p>I create beautiful  & functional websites, User interfaces and Corporate identity for small businesses.</p>
tagline:             Website designer and developer.
url:                 http://www.rahulkrishna.xyz
paginate:            1
baseurl:             "https://www.rahulkrishna.xyz"
logo:             http://res.cloudinary.com/rahulkrishna/image/upload/q_100/v1501565421/rahulkrishna.xyz/logo_big_dark_gtpaof.png
icon:                http://res.cloudinary.com/rahulkrishna/image/upload/v1501565421/rahulkrishna.xyz/logo64_dark_sggjjk.png

#collections
collections:
  works:
    output: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rahul Krishna
  url:               https://twitter.com/_RahulKrishna
  email:             rahul.krishna11@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
